org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

# Suppress Kotlin deprecation warnings (for nfc_manager compatibility)
kotlin.suppressWarnings=true
kotlin.daemon.jvmargs=-Xmx4G

# Disable Kotlin compiler warnings as errors
kotlin.compiler.suppressWarnings=true
